image: sparkfabrik/spark-k8s-deployer:latest

services:
  - docker:19.03-dind

stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  BASE_URL: www.paolomainardi.com


build:
  stage: build
  script:
    - make hugo-build
  artifacts:
    expire_in: 1 hour
    paths:
      - output/

deploy:
  image: node:10-alpine3.9
  stage: deploy
  script:
    - firebase deploy

